CREATE TABLE VRADDRESSES
(
    ID      VARCHAR(36),
    USER_ID VARCHAR(36),
    COUNTRY VARCHAR(128),
    CITY    VARCHAR(255),
    ZIP     VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE VRUSERS
(
    ID         VARCHAR(36)  NOT NULL,
    NAME       VARCHAR(128) NOT NULL,
    GENRE      VARCHAR(64)  NOT NULL,
    ADDRESS_ID VARCHAR(36),
    BIRTHDATE  DATE,
    ABOUT      VARCHAR(2048),
    PRIMARY KEY (ID),
    FOREIGN KEY (ADDRESS_ID) REFERENCES VRADDRESSES (ID) ON DELETE SET NULL
);

ALTER TABLE VRADDRESSES ADD CONSTRAINT FK_VRADDRESSES_VRUSERS FOREIGN KEY (USER_ID) REFERENCES VRUSERS (ID) ON DELETE CASCADE;
