CREATE TABLE VRPENDING_FRIENDSHIPS
(
    ID       VARCHAR(36) NOT NULL,
    SENDER   VARCHAR(36) NOT NULL,
    RECEIVER VARCHAR(36) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (SENDER, RECEIVER),
    FOREIGN KEY (SENDER) REFERENCES VRUSERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (RECEIVER) REFERENCES VRUSERS (ID) ON DELETE CASCADE
);

CREATE TABLE VRFRIENDSHIPS
(
    ID            VARCHAR(36) NOT NULL,
    USER1        VARCHAR(36) NOT NULL,
    USER2      VARCHAR(36) NOT NULL,
    FRIENDS_SINCE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (USER1, USER2),
    PRIMARY KEY (ID),
    FOREIGN KEY (USER1) REFERENCES VRUSERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (USER2) REFERENCES VRUSERS (ID) ON DELETE CASCADE
);