name: Release
on:
  push:
    branches:
      - master

jobs:
  Release:
    name: Deploy on vrabia server
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy settings xml file
        run: cp ${{ github.workspace }}/../../../settings.xml ${{ github.workspace }}/settings.xml
      - name: Copy envrc file
        run: cp ${{ github.workspace }}/../../../.envrc ${{ github.workspace }}/.envrc
      - name: Restart docker service
        run: docker compose up --build -d

